import { GridConfig } from '../../validators/config';
import { generateVpc } from './vpc';
import { generateSubnet } from './subnet';
import { generateVm } from './vm';
import path from 'path';
import fs from 'fs-extra';

export interface GenerateOptions {
  outputDir: string;
  format: 'terraform' | 'opentofu';
}

export interface GenerateResult {
  fileCount: number;
  files: string[];
  warnings?: string[];
}

/**
 * Generate Terraform/OpenTofu files from Grid configuration
 */
export async function generateInfrastructure(
  config: GridConfig,
  options: GenerateOptions
): Promise<GenerateResult> {
  const files: string[] = [];
  const warnings: string[] = [];

  // Ensure output directory exists
  await fs.ensureDir(options.outputDir);

  // Generate main Terraform file
  const mainTfPath = path.join(options.outputDir, 'main.tf');
  let mainTfContent = generateHeader(config, options.format);
  
  // Generate provider configuration
  mainTfContent += generateProvider(config);
  
  // Generate resources
  const resourceMap = new Map<string, string>();
  
  for (const resource of config.resources) {
    let resourceContent = '';
    
    switch (resource.type) {
      case 'vpc':
        resourceContent = generateVpc(resource);
        break;
      case 'subnet':
        resourceContent = generateSubnet(resource, config.provider);
        break;
      case 'vm':
        resourceContent = generateVm(resource, config.provider);
        break;
      default:
        warnings.push(`Unknown resource type: ${resource.type}`);
        continue;
    }
    
    resourceMap.set(resource.name, resourceContent);
  }

  // Order resources: VPCs first, then subnets, then VMs
  const vpcs = config.resources.filter(r => r.type === 'vpc');
  const subnets = config.resources.filter(r => r.type === 'subnet');
  const vms = config.resources.filter(r => r.type === 'vm');

  vpcs.forEach(vpc => {
    mainTfContent += resourceMap.get(vpc.name) + '\n\n';
  });
  
  subnets.forEach(subnet => {
    mainTfContent += resourceMap.get(subnet.name) + '\n\n';
  });
  
  vms.forEach(vm => {
    mainTfContent += resourceMap.get(vm.name) + '\n\n';
  });

  // Write main.tf
  await fs.writeFile(mainTfPath, mainTfContent);
  files.push(mainTfPath);

  // Generate outputs.tf
  const outputsTfPath = path.join(options.outputDir, 'outputs.tf');
  const outputsContent = generateOutputs(config);
  await fs.writeFile(outputsTfPath, outputsContent);
  files.push(outputsTfPath);

  // Generate variables.tf (if needed)
  const variablesTfPath = path.join(options.outputDir, 'variables.tf');
  const variablesContent = generateVariables(config);
  await fs.writeFile(variablesTfPath, variablesContent);
  files.push(variablesTfPath);

  return {
    fileCount: files.length,
    files,
    warnings: warnings.length > 0 ? warnings : undefined,
  };
}

function generateHeader(config: GridConfig, format: 'terraform' | 'opentofu'): string {
  const tool = format === 'opentofu' ? 'OpenTofu' : 'Terraform';
  return `# ${tool} configuration generated by Grid Platform
# Provider: ${config.provider.toUpperCase()}
# Project: ${config.project}

`;
}

function generateProvider(config: GridConfig): string {
  switch (config.provider) {
    case 'gcp':
      return `terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.0"
}

provider "google" {
  project = "${config.project}"
  region  = "${config.region || 'us-central1'}"
}

`;
    case 'aws':
      return `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.0"
}

provider "aws" {
  region = "${config.region || 'us-east-1'}"
}

`;
    case 'azure':
      return `terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.0"
}

provider "azurerm" {
  features {}
}

`;
    default:
      throw new Error(`Unsupported provider: ${config.provider}`);
  }
}

function generateOutputs(config: GridConfig): string {
  let content = '# Outputs\n\n';
  
  config.resources.forEach(resource => {
    if (resource.type === 'vpc') {
      content += `output "${resource.name}_vpc_id" {
  description = "VPC ID for ${resource.name}"
  value       = ${config.provider === 'gcp' ? 'google_compute_network' : 'aws_vpc'}.${resource.name}.id
}

`;
    }
  });
  
  return content;
}

function generateVariables(config: GridConfig): string {
  return `# Variables\n\nvariable "project" {
  description = "Project ID/Name"
  type        = string
  default     = "${config.project}"
}

variable "region" {
  description = "Region"
  type        = string
  default     = "${config.region || (config.provider === 'gcp' ? 'us-central1' : 'us-east-1')}"
}

`;
}

