import path from 'path';
import fs from 'fs-extra';
import { GridConfig, isComposerResource, isGenericResource } from '../../validators/config';
import { generateBackend } from './backend';
import { moduleSpecsFromResources, renderCatalogResources } from './catalogResources';
import { ModuleCopySpec, copyModulesFromBank, resolveModuleBankRoot } from './moduleBank';
import { bootstrapProviders } from '../../providers';
import { assertProviderCanGenerate } from '../../providers/registry';

export interface GenerateOptions {
  outputDir: string;
  format: 'terraform' | 'opentofu';
}

export interface GenerateResult {
  fileCount: number;
  files: string[];
  warnings?: string[];
}

/**
 * Generate Terraform/OpenTofu files from a Grid JSON config.
 * Modules are copied from grid-terraform (Grid product module bank).
 *
 * Two rendering paths:
 * - vpc / subnet / vm go through the ProviderAdapter composers, which build the
 *   network graph and wire VMs to subnets and security groups.
 * - every other catalogued type goes through the generic catalog path, which
 *   emits one module block per resource with its config forwarded as variables.
 *
 * Cloud-specific logic lives in ProviderAdapter — add a new cloud by registering one.
 */
export async function generateInfrastructure(
  config: GridConfig,
  options: GenerateOptions
): Promise<GenerateResult> {
  bootstrapProviders();
  const provider = assertProviderCanGenerate(config.provider);

  const files: string[] = [];
  const warnings: string[] = [];
  const region = config.region || provider.defaultRegion;

  await fs.ensureDir(options.outputDir);
  const modulesTarget = path.join(options.outputDir, 'modules');
  await fs.emptyDir(modulesTarget);

  const bankRoot = resolveModuleBankRoot();
  warnings.push(`Using Grid module bank: ${bankRoot}`);

  const composerResources = config.resources.filter(isComposerResource);
  const catalogResources = config.resources.filter(isGenericResource);
  const composerConfig: GridConfig = { ...config, resources: composerResources };

  const blocks: string[] = [];
  const specs: ModuleCopySpec[] = [];

  if (composerResources.length > 0) {
    blocks.push(provider.renderResources(composerConfig, region));
    specs.push(...provider.moduleSpecsForGenerate);
  }

  if (catalogResources.length > 0) {
    blocks.push(
      renderCatalogResources(provider.id, catalogResources, {
        project: config.project,
        region,
      })
    );
    specs.push(...moduleSpecsFromResources(provider.id, catalogResources));
  }

  const resourceBlocks = blocks.filter((block) => block.trim().length > 0).join('\n\n');
  const outputs =
    composerResources.length > 0 ? provider.renderOutputs(composerConfig) : '# Outputs\n';
  const copied = await copyModulesFromBank(modulesTarget, dedupeSpecs(specs));
  warnings.push(`Copied modules: ${copied.join(', ') || '(none)'}`);

  const header = `# ${options.format === 'opentofu' ? 'OpenTofu' : 'Terraform'} configuration generated by Grid Platform
# Provider: ${provider.label} (${provider.id})
# Project: ${config.project}
# Module bank: ${bankRoot}

`;

  const mainTfPath = path.join(options.outputDir, 'main.tf');
  await fs.writeFile(mainTfPath, `${header}${resourceBlocks}\n`);
  files.push(mainTfPath);

  const providerTfPath = path.join(options.outputDir, 'provider.tf');
  await fs.writeFile(providerTfPath, provider.renderProviderBlock(config));
  files.push(providerTfPath);

  const backendTfPath = path.join(options.outputDir, 'backend.tf');
  await fs.writeFile(backendTfPath, generateBackend(config));
  files.push(backendTfPath);

  const outputsTfPath = path.join(options.outputDir, 'outputs.tf');
  await fs.writeFile(outputsTfPath, outputs);
  files.push(outputsTfPath);

  const variablesTfPath = path.join(options.outputDir, 'variables.tf');
  await fs.writeFile(variablesTfPath, renderVariables(config, region));
  files.push(variablesTfPath);

  return {
    fileCount: files.length,
    files,
    warnings: warnings.length > 0 ? warnings : undefined,
  };
}

/** A composer module and a catalogued type can point at the same bank module. */
function dedupeSpecs(specs: ModuleCopySpec[]): ModuleCopySpec[] {
  const byDest = new Map<string, ModuleCopySpec>();
  for (const spec of specs) {
    if (!byDest.has(spec.destPath)) byDest.set(spec.destPath, spec);
  }
  return [...byDest.values()];
}

function renderVariables(config: GridConfig, region: string): string {
  return `variable "project" {
  description = "Project ID / account label"
  type        = string
  default     = "${config.project}"
}

variable "region" {
  description = "Cloud region"
  type        = string
  default     = "${region}"
}
`;
}
