import path from 'path';
import fs from 'fs-extra';
import { GridConfig } from '../../validators/config';
import { generateBackend } from './backend';
import { moduleSpecsFromResources, renderCatalogResources } from './catalogResources';
import { ModuleCopySpec, copyModulesFromBank, resolveModuleBankRoot } from './moduleBank';
import { bootstrapProviders } from '../../providers';
import { assertProviderCanGenerate } from '../../providers/registry';

export interface GenerateOptions {
  outputDir: string;
  format: 'terraform' | 'opentofu';
}

export interface GenerateResult {
  fileCount: number;
  files: string[];
  warnings?: string[];
}

/**
 * Generate Terraform/OpenTofu from Grid JSON.
 *
 * One path for every cloud: resourceCatalog → catalogResources → module bank.
 * I/O: module install + file writes run in parallel where safe.
 */
export async function generateInfrastructure(
  config: GridConfig,
  options: GenerateOptions
): Promise<GenerateResult> {
  bootstrapProviders();
  const provider = assertProviderCanGenerate(config.provider);

  const warnings: string[] = [];
  const region = config.region || provider.defaultRegion;

  const bankRoot = resolveModuleBankRoot();
  if (!(await fs.pathExists(bankRoot))) {
    throw new Error(
      `Grid Terraform module bank not found at ${bankRoot}. ` +
        `Expected sibling repo grid-terraform, or set GRID_MODULE_BANK.`
    );
  }
  warnings.push(`Using Grid module bank: ${bankRoot}`);

  let resourceBlocks: string;
  try {
    resourceBlocks = renderCatalogResources(provider.id, config.resources, {
      project: config.project,
      region,
    });
  } catch (error) {
    throw new Error(
      `Generate failed for provider "${provider.id}": ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }

  const specs = dedupeSpecs(moduleSpecsFromResources(provider.id, config.resources));

  await fs.ensureDir(options.outputDir);
  const modulesTarget = path.join(options.outputDir, 'modules');
  await fs.emptyDir(modulesTarget);

  const header = `# ${options.format === 'opentofu' ? 'OpenTofu' : 'Terraform'} configuration generated by Grid Platform
# Provider: ${provider.label} (${provider.id})
# Project: ${config.project}
# Module bank: ${bankRoot}

`;

  const mainTfPath = path.join(options.outputDir, 'main.tf');
  const providerTfPath = path.join(options.outputDir, 'provider.tf');
  const backendTfPath = path.join(options.outputDir, 'backend.tf');
  const outputsTfPath = path.join(options.outputDir, 'outputs.tf');
  const variablesTfPath = path.join(options.outputDir, 'variables.tf');

  // Modules + generated files in parallel (CPU render already done).
  const [install] = await Promise.all([
    copyModulesFromBank(modulesTarget, specs),
    fs.writeFile(mainTfPath, `${header}${resourceBlocks}\n`),
    fs.writeFile(providerTfPath, provider.renderProviderBlock(config)),
    fs.writeFile(backendTfPath, generateBackend(config)),
    fs.writeFile(outputsTfPath, '# Outputs\n'),
    fs.writeFile(variablesTfPath, renderVariables(config, region)),
  ]);

  const verb = install.mode === 'link' ? 'Linked' : 'Copied';
  warnings.push(`${verb} modules: ${install.installed.join(', ') || '(none)'}`);
  if (install.mode === 'link') {
    warnings.push('Modules are symlinked (fast). Set GRID_MODULE_COPY=1 for a full copy.');
  }

  const files = [mainTfPath, providerTfPath, backendTfPath, outputsTfPath, variablesTfPath];

  return {
    fileCount: files.length,
    files,
    warnings,
  };
}

function dedupeSpecs(specs: ModuleCopySpec[]): ModuleCopySpec[] {
  const byDest = new Map<string, ModuleCopySpec>();
  for (const spec of specs) {
    if (!byDest.has(spec.destPath)) byDest.set(spec.destPath, spec);
  }
  return [...byDest.values()];
}

function renderVariables(config: GridConfig, region: string): string {
  return `variable "project" {
  description = "Project ID / account label"
  type        = string
  default     = "${config.project}"
}

variable "region" {
  description = "Cloud region"
  type        = string
  default     = "${region}"
}
`;
}
